apiVersion: v1
kind: Service
metadata:
  name: deployment-tracker-app
  namespace: deployment-tracker
spec:
  type: NodePort
  selector:
    app: deployment-tracker-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
